### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by thanhngvpt** [HarshdeepGupta/live-html-preview#1]
Hello author.
when i run command show side preview it display error 
"command 'extension.sidePreview" not found

Please help me.
Thanks

**Comment by soulchainer** [comment]
Same issue here. Phew. This is awaiting some answer from August. You get it solved somehow, @thanhngvpt?
Are you using some other extension that works (on the side)?

**Comment by b3n10** [comment]
I'm also using Arch Linux and getting this same error.

**Comment by joeysys** [comment]
in Utilities.js:
change
`var previewManager_1 = require('./previewManager');`
to
`var previewManager_1 = require('./PreviewManager');`

**Comment by chiccofra** [comment]
this change doesn't work.
do you have any news? The code in the file is:

"use strict";
var vscode = require('vscode');
var PreviewManager_1 = require('./PreviewManager');
var Constants = require('./Constants');
var Utilities = (function () {
    //returns true if an html document is open
    function Utilities() {
    }
    ;
    Utilities.prototype.checkDocumentIsHTML = function (showWarning) {
        var result = vscode.window.activeTextEditor.document.languageId.toLowerCase() === "html";
        if (!result && showWarning) {
            vscode.window.showInformationMessage(Constants.ErrorMessages.NO_HTML);
        }
        return result;
    };
    Utilities.prototype.init = function (viewColumn, context, previewUri) {
        var proceed = this.checkDocumentIsHTML(true);
        if (proceed) {
            var previewManager = new PreviewManager_1.default();
            var registration = vscode.workspace.registerTextDocumentContentProvider('HTMLPreview', previewManager.htmlDocumentContentProvider);
            return vscode.commands.executeCommand('vscode.previewHtml', previewUri, viewColumn).then(function (success) {
            });
        }
    };
    return Utilities;
}());
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = Utilities;
//# sourceMappingURL=Utilities.js.map

**Comment by HarshdeepGupta** [comment]
@joeysys the method works, Thanks

**Comment by GratefulDave** [comment]
I'm relatively new to vs code and working with Python . Where can I find the utilities.js file?
