### ISSUE TITLE
The background color is black.

### ISSUE THREAD

**Issue by BeginnerGitHub** [HarshdeepGupta/live-html-preview#10]
Hi,
I installed the plugin, it works well but there is a problem: the background color is black.

I uninstalled the plugin then I installed it again but the problem persists ...

I'm a beginner with VScode ...
Is there a configuration to be made?

Thank you.

**Comment by HarshdeepGupta** [comment]
Can you tell me the details of your system, because I cann't replicate the issue on my windows machine. Apart from that, there is no configuration to be made. Also, VScode has a dark theme by default.

I suggest you try changing the background color of your webpage.

**Comment by BeginnerGitHub** [comment]
Thank you.
I have Windows 7 64bits and VSCode 1.14.2.

Thank you for your suggestion. I also had this idea, for now I add CSS style:

body {
           background-color: white;
           color: black;
        }

It works well...
