### ISSUE TITLE
Show preview when cursor is at non HTML file

### ISSUE THREAD

**Issue by Horray** [HarshdeepGupta/live-html-preview#5]
This is a great plugin! Really well done!

When the cursor goes on a JavaScript file, the preview window shows the actual JavaScript text. It doesn't show the outcome of the HTML.

Is there anything I can do to make it show an actual live preview of the HTML document, even when the cursor is at a non HTML file?

**Comment by Mikael-Sundstrom** [comment]
Same thing happens to css files. I want a solution for that too.
I really like the plugin, well done.

**Comment by HAlexTM** [comment]
Pull request #12 will fix the issue
