### ISSUE TITLE
changes in external CSS doesn't update preview

### ISSUE THREAD

**Issue by wheelhot** [HarshdeepGupta/live-html-preview#6]
Not sure why, but if I were to change my css, like the colours, it'll not reflect in the HTML preview window, if I were to open in browser, I can see that the changes is done correctly

**Comment by HarshdeepGupta** [comment]
Fixed in the update.

**Comment by pito-svk** [comment]
Also not working for me.

I have this reference in my html file:

```html
<head>
  <link rel="stylesheet" href="app.css">
</head>
```

And on any css changes I have to restart live previewer.
