### ISSUE TITLE
This extension uses the cmd+Q combination which usually used for exit vscode.

### ISSUE THREAD

**Issue by ranyitz** [HarshdeepGupta/live-html-preview#7]
when you install the extension you cannot perform cmd+Q in order to exit vscode.

we should consider changing the command keys maybe to alt+shift + Q.

https://github.com/HarshdeepGupta/live-html-preview/blob/master/package.json#L65-L84

**Comment by VReality64** [comment]
I agree. It's very important. hope this done ASSP.
or maybe it might not need to have shortcut.

**Comment by HarshdeepGupta** [comment]
Thanks to @kaiwood , this issue has been fixed in the update.
